tomcat7:
  build: tomcat7
  hostname: tomcat7
  ports:
    - "8080:8080"
  links:
    - graylogserver:graylog
    - jbossas7:jbossas7
  mem_limit: 128m

jbossas7:
  build: jbossas7
  hostname: jbossas7
  ports:
    - "8081:8080"
    - "9990:9990"
  links:
    - graylogserver:graylog
  mem_limit: 256m

graylogserver:
  build: graylog/server
  hostname: graylogserver
  links:
   - graylogmongodb:mongo
   - elasticsearch:elasticsearch
  ports:
   - "12900:12900"

graylogweb:
  build: graylog/web
  hostname: graylogweb
  links:
   - graylogserver:graylog
  ports:
   - "9000:9000"

graylogmongodb:
  build: graylog/mongodb
  hostname: graylogmongodb
  mem_limit: 128m

elasticsearch:
  build: elasticsearch
  hostname: elasticsearch
