tomcat7:
  build: tomcat7
  hostname: tomcat7
  ports:
    - "8080:8080"
  links:
    - logstash:logstash
    - jbossas7:jbossas7
  mem_limit: 128m

jbossas7:
  build: jbossas7
  hostname: jbossas7
  ports:
    - "8081:8080"
    - "9990:9990"
  links:
    - logstash:logstash
  mem_limit: 256m

elasticsearch:
  image: deviantony/elk-elasticsearch
  ports:
    - "9200:9200"
logstash:
  image: deviantony/elk-logstash
  volumes:
    - logstash-conf:/etc/logstash/conf.d
  ports:
    - "514/udp"
    - "514/tcp"
    - "12201/udp"
    - "12201/tcp"
  links:
    - elasticsearch
kibana4:
  build: docker-elk-kibana
  ports:
    - "5601:5601"
  links:
    - elasticsearch
